### ISSUE TITLE
Expected format for ALTO should include "application/alto+xml"

### ISSUE THREAD

**Issue by lutzhelm** [dbmdz/mirador-textoverlay#167]
Neither `application/alto+xml` nor `application/xml+alto` (which is currently evaluated and mentioned in the README) are official [media types](https://www.iana.org/assignments/media-types/media-types.xhtml#application), but there is a (somewhat older) discussion in altoxml/schema#40 that suggests `application/alto+xml` as `format` option inclusion of ALTO via `seeAlso`. Also, `application/alto+xml` follows the pattern of other `application/xml` media types.

If you agree, I could provide a PR offering `application/alto+xml` as an _additional_ option.

**Comment by jbaiter** [comment]
Absolutely, thank you!
