### ISSUE TITLE
Add support for underlying SVG transformations

### ISSUE THREAD

**Issue by stefan-it** [dbmdz/mirador-textoverlay#24]
Hi,

it would be awesome to have support for svg transformations. E.g. when using the [Mirador Image Tools](https://github.com/ProjectMirador/mirador-image-tools), that e.g. support flipping or rotating images:

![image](https://user-images.githubusercontent.com/20651387/88678009-46646580-d0ee-11ea-9918-253f47e17998.png)

**Comment by jbaiter** [comment]
This has been implemented in #26
