### ISSUE TITLE
Textoverlay is on the wrong canvas

### ISSUE THREAD

**Issue by ulb-sa-schmilj** [dbmdz/mirador-textoverlay#57]
IIIF manifest is attached.
[text-overlay.zip](https://github.com/dbmdz/mirador-textoverlay/files/5963756/text-overlay.zip)
(https://dev.opendata.uni-halle.de//json/iiif/123456789/21145/21e5d46a-1eac-4ec1-bc32-57e7f79bbb9c/manifest)

There are the following canvases:
- Canvas with label "[Seite 3]" with no fulltext
- Canvas with label "[Seite 4]" with no fulltext
- Canvas with label "[Seite 5]" with fulltext
- ...

But the fulltext of [Seite 5] is shown on [Seite 4].
![2021-02-11 09_17_45-mirador-textoverlay 0 3 2 Demo](https://user-images.githubusercontent.com/54576195/107614180-158eec80-6c4a-11eb-89b7-868154b410f7.png)

The fulltext for "[Seite 6]" is correct shown.

dev.opendata.uni-halle.de have a restricted IP whitelist. @jbaiter I can add your IP for access to the manifest and the images...

**Comment by jbaiter** [comment]
Thanks for reporting!
Does this only happen in the 2-up "book view" or also in the single page view?
I'll stub out the image URLs for debugging, this bug is most likely not related to them, so, no need to give me access to your internal systems :-)

**Comment by ulb-sa-schmilj** [comment]
The bug exists NOT in the single page view.
